name: run data_extraction

on:
  schedule:
    - cron: '0 21 * * *'  # Every day at 21:00

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2  # Revisa el contenido del repositorio

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Define la versión de Python

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala las dependencias del archivo

      - name: Execute Python script
        run: python DataExtraction/main.py  # Ejecuta el script main.py en el directorio DataExtraction

      - name: commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Pull changes
        run: |
          git pull --rebase origin main  # Hacer pull con rebase para integrar cambios remotos

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main